# Generated by Django 3.0.3 on 2020-02-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Sex', models.CharField(max_length=2)),
                ('Job', models.CharField(max_length=10)),
                ('Age', models.PositiveIntegerField()),
                ('Birth_Place', models.CharField(max_length=100)),
                ('Residence', models.CharField(max_length=100)),
                ('STR', models.PositiveIntegerField()),
                ('CON', models.PositiveIntegerField()),
                ('SIZ', models.PositiveIntegerField()),
                ('DEX', models.PositiveIntegerField()),
                ('APP', models.PositiveIntegerField()),
                ('EDU', models.PositiveIntegerField()),
                ('INT', models.PositiveIntegerField()),
                ('POW', models.PositiveIntegerField()),
                ('MOV', models.PositiveIntegerField()),
            ],
        ),
    ]
