# Generated by Django 3.0.3 on 2020-02-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Sex',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
